# Generated by Django 5.0 on 2023-12-27 21:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('splittime', '0004_expense'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='creation_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='creation_date'),
            preserve_default=False,
        ),
    ]
