# Generated by Django 5.0 on 2023-12-28 00:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('splittime', '0006_alter_groupmembership_member_debt_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='payee',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='payee', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
