# Generated by Django 5.0 on 2024-01-02 08:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('splittime', '0007_expense_payee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debt',
            name='ratio',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
