// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/welcome": {
    params: {};
  };
  "/auth/login": {
    params: {};
  };
  "/auth/logout": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/welcome" | "/auth/login" | "/auth/logout";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "welcome/welcome.tsx": {
    id: "welcome/welcome";
    page: "/welcome";
  };
  "auth/Login.tsx": {
    id: "auth/Login";
    page: "/auth/login";
  };
  "auth/Logout.tsx": {
    id: "auth/Logout";
    page: "/auth/logout";
  };
};