# Generated by Django 5.0 on 2023-12-08 22:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('splittime', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 8, 22, 54, 49, 893965, tzinfo=datetime.timezone.utc), verbose_name='creation date'),
            preserve_default=False,
        ),
    ]
