# Generated by Django 5.0 on 2024-01-03 01:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('splittime', '0008_alter_debt_ratio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debt',
            name='ratio',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
